### ISSUE TITLE
Cannot get DKIM working

### ISSUE THREAD

**Issue by borostreet** [jeboehm/mailserver-admin#48]
Running https://github.com/jeboehm/docker-mailserver/
Cannot get DKIM working
Follow the Wiki for DKIM https://github.com/jeboehm/docker-mailserver/wiki/Feature:-DKIM

mailserver-admin never shows correct DKIM
nor 
 DKIM is enabled but not properly set up. Your mails may be rejected on the receivers side. Check your DNS settings.
ever goes away.

**To Reproduce**
1. follow wiki here: https://github.com/jeboehm/docker-mailserver/wiki/Feature:-DKIM

**Expected behavior**
Expect to see "Record Valid = YES"

**Screenshots**
Domain:
2021070101._domainkey.x.zocto.com
Record type:
TXT
Expected value:

v=DKIM1\; h=sha256\; t=s\;
p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCg
KCAQEA0Pz2wdSsvFCo+Xpvx57HSckiacJPmg6tiG
rE+aRe7jWGezqxsCdlX4TLuXxYa/pTROKRP6avVY
zsaMOu3rnfi+oEMpcK8zywf0vEQaG+8W8Euzr0kO
ibZwa/obWv8ZSWWZ/l4XqpCYMG0wEtmlkp9/FLZF
bX7WIAs0qxiD8jDMe/n1plBNFg8CFVah3tEDumO6
/vPt9eS2qqzfdwMrqooV3+cASm/CB72OnVGP3rT0
Ras0beM8evbLb199o6LftfFRBqg4utoexfXOAFAo
eRhptZsMnSgCseCrBcGuQw5SR6dQ4zFOD662sS39
/lTOtf2tE5bSxk4FIxQ7gxOOMCUQIDAQAB

Current value:

v=DKIM1\; h=sha256\; t=s\;
p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCg
KCAQEA0Pz2wdSsvFCo+Xpvx57HSckiacJPmg6tiG
rE+aRe7jWGezqxsCdlX4TLuXxYa/pTROKRP6avVY
zsaMOu3rnfi+oEMpcK8zywf0vEQaG+8W8Euzr0kO
ibZwa/obWv8ZSWWZ/l4XqpCYMG0wEtmlkp9/FLZF
bX7WIAs0qxiD8jDMe/n1plBNFg8CFVah3tEDumO6
/vPt9eS2qqzfdwMrqooV3+cASm/CB72OnVGP3rT0
Ras0beM8evbLb199o6LftfFRBqg4utoexfXOAFAo
eRhptZsMnSgCseCrBcGuQw5SR6dQ4zFOD662sS39
/lTOtf2tE5bSxk4FIxQ7gxOOMCUQIDAQAB

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox

**Smartphone (please complete the following information):**
- N/a
**Additional context**

**Comment by jeboehm** [comment]
Running `dig TXT 2021070101._domainkey.x.zocto.com` shows

`;; ANSWER SECTION:
2021070101._domainkey.x.zocto.com. 3600	IN TXT	"v=DKIM1; h=sha256; t=s; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCg KCAQEA0Pz2wdSsvFCo+Xpvx57HSckiacJPmg6tiG rE+aRe7jWGezqxsCdlX4TLuXxYa/pTROKRP6avVY zsaMOu3rnfi+oEMpcK8zywf0vEQaG+8W8Euzr0kO ibZwa/obWv8ZSWWZ/l4XqpCYMG0wEtmlkp9/FLZF bX7WIAs0qxiD8jDMe/n1plBNFg" "8CFVah3tEDumO6 /vPt9eS2qqzfdwMrqooV3+cASm/CB72OnVGP3rT0 Ras0beM8evbLb199o6LftfFRBqg4utoexfXOAFAo eRhptZsMnSgCseCrBcGuQw5SR6dQ4zFOD662sS39 /lTOtf2tE5bSxk4FIxQ7gxOOMCUQIDAQAB"`

**Comment by borostreet** [comment]
Still see no issue in the DKIM record quotes are concatenated.
dig == dns TXT record
I did see expected change as I refreshed page.

What also seems strange is that emails sent when I manually configure:
https://workaround.org/ispmail/buster/prevent-spoofing-using-dkim/
which is what I expect the manager would do.
Still no record in outgoing email.

Thanks for your attention.

**Comment by borostreet** [comment]
Rephrase: I did see "current value" change as I refreshed page.  Which may be a DNS server issue.

**Comment by borostreet** [comment]
Turning on debug helped
/ # cat /etc/rspamd/local.d/logging.inc
type = file
filename = /var/log/rspamd/r.log

Docs seem incorrect
/ # cat /etc/rspamd/local.d/dkim_signing.conf
path = "/media/dkim/$domain.$selector.key";
selector_map = "/media/dkim/dkim_selectors.map";

/ # cat /media/dkim/dkim_selectors.map
x.zotco.com 2021070101

Create key in
  /media/dkim/x.zocto.com.2021070101.key
**NOGO**

logs indicate 
2021-07-05 02:32:05 #21(normal) <541aa1>; task; dkim_module_load_key_format: cannot load dkim key /media/dkim/zocto.com.dkim.key: cannot stat key file: '/media/dkim/zocto.com.dkim.key' No such file or directory

Moved key to **/media/dkim/zocto.com.dkim.key** **_(which seems incorrect.)_**
**PASS**
